#!/usr/bin/env python3
"""Render docker deployment artifacts from application env references.

This renderer treats backend/frontend env references as the single source of
truth for application env examples and uses shared docker compose templates for
docker-only orchestration defaults.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


DOCKER_ROOT = Path(__file__).resolve().parent
BACKEND_REFERENCE_PATH = DOCKER_ROOT.parent / "api" / "docs" / "backend-env.reference.json"
FRONTEND_REFERENCE_PATH = DOCKER_ROOT.parent / "web" / "docs" / "frontend-env.reference.json"
MAIN_TEMPLATE_PATH = DOCKER_ROOT / "docker-compose-template.yaml"
SHARED_SERVICES_TEMPLATE_PATH = DOCKER_ROOT / "compose-source" / "shared-docker-services.template.yaml"
MIDDLEWARE_TEMPLATE_PATH = DOCKER_ROOT / "compose-source" / "docker-compose.middleware.template.yaml"
MIDDLEWARE_ENV_CONFIG_PATH = DOCKER_ROOT / "compose-source" / "middleware-env.json"

DEFAULT_ENV_OUTPUT_PATH = DOCKER_ROOT / ".env.example"
MIDDLEWARE_ENV_OUTPUT_PATH = DOCKER_ROOT / "middleware.env.example"
MAIN_COMPOSE_OUTPUT_PATH = DOCKER_ROOT / "docker-compose.yaml"
MIDDLEWARE_COMPOSE_OUTPUT_PATH = DOCKER_ROOT / "docker-compose.middleware.yaml"

PLACEHOLDER_PATTERN = re.compile(r"{{([A-Z0-9_]+)}}")

ENV_WARNING_HEADER = (
    "# ==================================================================\n"
    "# WARNING: This file is auto-generated by render_deployment_configs.py\n"
    "# Do not modify this file directly. Update the backend/frontend env\n"
    "# reference sources or compose-source inputs, then regenerate this file.\n"
    "# ==================================================================\n"
)

COMPOSE_WARNING_HEADER = (
    "# ==================================================================\n"
    "# WARNING: This file is auto-generated by generate_docker_compose\n"
    "# Do not modify this file directly. Update docker-compose-template.yaml,\n"
    "# compose-source templates, or env references, then regenerate this file.\n"
    "# ==================================================================\n"
)


class RenderError(RuntimeError):
    """Raised when rendering inputs are invalid."""


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _normalize_description(description: Any) -> str:
    normalized = " ".join(str(description or "").split())
    return re.sub(r"([.!?;:])(?=[A-Za-z`])", r"\1 ", normalized)


def _validate_deployment_mode(variable_name: str, deployment: Any, scope_name: str) -> str:
    if not isinstance(deployment, dict):
        raise RenderError(
            f"{variable_name} is missing deployment metadata. Regenerate the env references before rendering."
        )
    mode = deployment.get(scope_name)
    if mode not in {"required", "omit"}:
        raise RenderError(f"{variable_name} has invalid deployment metadata: {scope_name}={mode!r}")
    return mode


def _load_reference_variables(path: Path) -> list[dict[str, Any]]:
    payload = _load_json(path)
    variables = payload.get("variables")
    if not isinstance(variables, list):
        raise RenderError(f"{path.name} does not contain a variables list")
    for variable in variables:
        if not isinstance(variable, dict) or "name" not in variable:
            raise RenderError(f"{path.name} contains an invalid variable entry")
        _validate_deployment_mode(variable["name"], variable.get("deployment"), "main_example")
        _validate_deployment_mode(variable["name"], variable.get("deployment"), "middleware_example")
    return variables


def _load_required_middleware_env_entries() -> list[dict[str, Any]]:
    payload = _load_json(MIDDLEWARE_ENV_CONFIG_PATH)
    variables = payload.get("variables", [])
    if not isinstance(variables, list):
        raise RenderError(f"{MIDDLEWARE_ENV_CONFIG_PATH.name} does not contain a variables list")

    required_entries: list[dict[str, Any]] = []
    for variable in variables:
        if not isinstance(variable, dict) or "name" not in variable:
            raise RenderError(f"{MIDDLEWARE_ENV_CONFIG_PATH.name} contains an invalid variable entry")
        mode = variable.get("middleware_example", "omit")
        if mode not in {"required", "omit"}:
            raise RenderError(
                f"{MIDDLEWARE_ENV_CONFIG_PATH.name} has invalid middleware_example for {variable['name']}: {mode!r}"
            )
        if mode == "required":
            required_entries.append(variable)
    return required_entries


def _required_reference_variables(variables: list[dict[str, Any]], scope_name: str) -> list[dict[str, Any]]:
    return [
        variable
        for variable in variables
        if _validate_deployment_mode(variable["name"], variable.get("deployment"), scope_name) == "required"
    ]


def _append_env_section(lines: list[str], title: str, variables: list[dict[str, Any]]) -> None:
    if not variables:
        return
    if len(lines) > 1:
        lines.append("")
    lines.extend([f"# {title}", ""])

    for index, variable in enumerate(variables):
        description = _normalize_description(variable.get("description"))
        if description:
            lines.append(f"# {description}")
        lines.append(f"{variable['name']}=")
        if index != len(variables) - 1:
            lines.append("")


def _append_middleware_env_section(lines: list[str], variables: list[dict[str, Any]]) -> None:
    if not variables:
        return
    if len(lines) > 1:
        lines.append("")
    lines.extend(["# Docker middleware environment", ""])

    for index, variable in enumerate(variables):
        description = _normalize_description(variable.get("description"))
        if description:
            lines.append(f"# {description}")
        render_value = variable.get("render_value", "")
        lines.append(f"{variable['name']}={render_value}")
        if index != len(variables) - 1:
            lines.append("")


def _render_default_env_file() -> str:
    backend_variables = _load_reference_variables(BACKEND_REFERENCE_PATH)
    frontend_variables = _load_reference_variables(FRONTEND_REFERENCE_PATH)

    lines: list[str] = [ENV_WARNING_HEADER.rstrip("\n")]
    _append_env_section(lines, "Backend application environment", _required_reference_variables(backend_variables, "main_example"))
    _append_env_section(lines, "Frontend application environment", _required_reference_variables(frontend_variables, "main_example"))
    return "\n".join(lines).rstrip() + "\n"


def _render_middleware_env_file() -> str:
    backend_variables = _load_reference_variables(BACKEND_REFERENCE_PATH)
    frontend_variables = _load_reference_variables(FRONTEND_REFERENCE_PATH)
    docker_variables = _load_required_middleware_env_entries()

    lines: list[str] = [ENV_WARNING_HEADER.rstrip("\n")]
    _append_env_section(
        lines,
        "Backend application environment for middleware local development",
        _required_reference_variables(backend_variables, "middleware_example"),
    )
    _append_env_section(
        lines,
        "Frontend application environment for middleware local development",
        _required_reference_variables(frontend_variables, "middleware_example"),
    )
    _append_middleware_env_section(lines, docker_variables)
    return "\n".join(lines).rstrip() + "\n"


def _render_template(template: str, context: dict[str, str]) -> str:
    rendered = template
    for key, value in context.items():
        rendered = rendered.replace(f"{{{{{key}}}}}", value)

    unresolved = sorted(set(PLACEHOLDER_PATTERN.findall(rendered)))
    if unresolved:
        unresolved_display = ", ".join(unresolved)
        raise RenderError(f"Unresolved compose placeholders: {unresolved_display}")
    return rendered


def _cleanup_rendered_compose(text: str) -> str:
    text = re.sub(r"(\n[ ]+[A-Za-z0-9_\"'-]+:\n)\n([ ]+\S)", r"\1\2", text)
    return re.sub(r"\n{3,}", "\n\n", text)


def _shared_services_context(target: str) -> dict[str, str]:
    if target == "main":
        return {
            "DB_POSTGRES_PROFILES": "    profiles:\n      - postgresql",
            "DB_POSTGRES_ENV_FILE": "",
            "DB_POSTGRES_ENVIRONMENT_LINES": (
                "      POSTGRES_USER: ${DB_USERNAME:-postgres}\n"
                "      POSTGRES_PASSWORD: ${DB_PASSWORD:-difyai123456}\n"
                "      POSTGRES_DB: ${DB_DATABASE:-dify}\n"
                "      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}"
            ),
            "DB_POSTGRES_VOLUME": "      - ./volumes/db/data:/var/lib/postgresql/data",
            "DB_POSTGRES_PORTS": "",
            "DB_POSTGRES_HEALTHCHECK_RETRIES": "60",
            "DB_MYSQL_PROFILES": "    profiles:\n      - mysql",
            "DB_MYSQL_ENV_FILE": "",
            "DB_MYSQL_VOLUME": "      - ${MYSQL_HOST_VOLUME:-./volumes/mysql/data}:/var/lib/mysql",
            "DB_MYSQL_PORTS": "",
            "REDIS_ENV_FILE": "",
            "REDIS_VOLUME": "      - ./volumes/redis/data:/data",
            "REDIS_PORTS": "",
            "SANDBOX_ENV_FILE": "",
            "PLUGIN_ENV_FILE": "",
            "PLUGIN_EXTRA_HOSTS": "",
            "PLUGIN_DIFY_INNER_API_URL_LINE": (
                "      DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}"
            ),
            "PLUGIN_FORCE_VERIFYING_SIGNATURE_LINE": (
                "      FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-true}"
            ),
            "PLUGIN_THIRD_PARTY_SIGNATURE_LINES": "",
            "PLUGIN_PORTS": '      - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"',
            "PLUGIN_DEPENDS_ON": (
                "    depends_on:\n"
                "      db_postgres:\n"
                "        condition: service_healthy\n"
                "        required: false\n"
                "      db_mysql:\n"
                "        condition: service_healthy\n"
                "        required: false\n"
                "      oceanbase:\n"
                "        condition: service_healthy\n"
                "        required: false\n"
                "      seekdb:\n"
                "        condition: service_healthy\n"
                "        required: false"
            ),
            "SSRF_ENV_FILE": "",
            "SSRF_PORTS": "",
            "WEAVIATE_PROFILES": "    profiles:\n      - weaviate",
            "WEAVIATE_ENV_FILE": "",
            "WEAVIATE_VOLUME": "      - ./volumes/weaviate:/var/lib/weaviate",
            "WEAVIATE_TOKENIZER_LINES": (
                "      ENABLE_TOKENIZER_GSE: ${WEAVIATE_ENABLE_TOKENIZER_GSE:-false}\n"
                "      ENABLE_TOKENIZER_KAGOME_JA: ${WEAVIATE_ENABLE_TOKENIZER_KAGOME_JA:-false}\n"
                "      ENABLE_TOKENIZER_KAGOME_KR: ${WEAVIATE_ENABLE_TOKENIZER_KAGOME_KR:-false}"
            ),
            "WEAVIATE_PORTS": "",
        }

    if target == "middleware":
        return {
            "DB_POSTGRES_PROFILES": '    profiles:\n      - ""\n      - postgresql',
            "DB_POSTGRES_ENV_FILE": "    env_file:\n      - ./middleware.env",
            "DB_POSTGRES_ENVIRONMENT_LINES": (
                "      POSTGRES_PASSWORD: ${DB_PASSWORD:-difyai123456}\n"
                "      POSTGRES_DB: ${DB_DATABASE:-dify}\n"
                "      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}"
            ),
            "DB_POSTGRES_VOLUME": "      - ${PGDATA_HOST_VOLUME:-./volumes/db/data}:/var/lib/postgresql/data",
            "DB_POSTGRES_PORTS": '    ports:\n      - "${EXPOSE_POSTGRES_PORT:-5432}:5432"',
            "DB_POSTGRES_HEALTHCHECK_RETRIES": "30",
            "DB_MYSQL_PROFILES": "    profiles:\n      - mysql",
            "DB_MYSQL_ENV_FILE": "    env_file:\n      - ./middleware.env",
            "DB_MYSQL_VOLUME": "      - ${MYSQL_HOST_VOLUME:-./volumes/mysql/data}:/var/lib/mysql",
            "DB_MYSQL_PORTS": '    ports:\n      - "${EXPOSE_MYSQL_PORT:-3306}:3306"',
            "REDIS_ENV_FILE": "    env_file:\n      - ./middleware.env",
            "REDIS_VOLUME": "      - ${REDIS_HOST_VOLUME:-./volumes/redis/data}:/data",
            "REDIS_PORTS": '    ports:\n      - "${EXPOSE_REDIS_PORT:-6379}:6379"',
            "SANDBOX_ENV_FILE": "    env_file:\n      - ./middleware.env",
            "PLUGIN_ENV_FILE": "    env_file:\n      - ./middleware.env",
            "PLUGIN_EXTRA_HOSTS": '    extra_hosts:\n      - "host.docker.internal:host-gateway"',
            "PLUGIN_DIFY_INNER_API_URL_LINE": (
                "      DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://host.docker.internal:5001}"
            ),
            "PLUGIN_FORCE_VERIFYING_SIGNATURE_LINE": (
                "      FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-false}"
            ),
            "PLUGIN_THIRD_PARTY_SIGNATURE_LINES": (
                "      THIRD_PARTY_SIGNATURE_VERIFICATION_ENABLED: true\n"
                "      THIRD_PARTY_SIGNATURE_VERIFICATION_PUBLIC_KEYS: /app/keys/publickey.pem"
            ),
            "PLUGIN_PORTS": (
                '      - "${EXPOSE_PLUGIN_DAEMON_PORT:-5002}:${PLUGIN_DAEMON_PORT:-5002}"\n'
                '      - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"'
            ),
            "PLUGIN_DEPENDS_ON": "",
            "SSRF_ENV_FILE": "    env_file:\n      - ./middleware.env",
            "SSRF_PORTS": (
                '    ports:\n'
                '      - "${EXPOSE_SSRF_PROXY_PORT:-3128}:${SSRF_HTTP_PORT:-3128}"\n'
                '      - "${EXPOSE_SANDBOX_PORT:-8194}:${SANDBOX_PORT:-8194}"'
            ),
            "WEAVIATE_PROFILES": '    profiles:\n      - ""\n      - weaviate',
            "WEAVIATE_ENV_FILE": "    env_file:\n      - ./middleware.env",
            "WEAVIATE_VOLUME": "      - ${WEAVIATE_HOST_VOLUME:-./volumes/weaviate}:/var/lib/weaviate",
            "WEAVIATE_TOKENIZER_LINES": "",
            "WEAVIATE_PORTS": (
                '    ports:\n'
                '      - "${EXPOSE_WEAVIATE_PORT:-8080}:8080"\n'
                '      - "${EXPOSE_WEAVIATE_GRPC_PORT:-50051}:50051"'
            ),
        }

    raise RenderError(f"Unsupported shared services target: {target}")


def _render_compose(target: str, template_path: Path) -> str:
    shared_services = _render_template(_load_text(SHARED_SERVICES_TEMPLATE_PATH), _shared_services_context(target))
    rendered = _render_template(_load_text(template_path), {"SHARED_DOCKER_SERVICES": shared_services})
    cleaned = _cleanup_rendered_compose(rendered)
    return f"{COMPOSE_WARNING_HEADER}\n{cleaned.lstrip()}"


def _write_if_changed(path: Path, content: str) -> bool:
    previous = path.read_text(encoding="utf-8") if path.exists() else None
    if previous == content:
        return False
    with path.open("w", encoding="utf-8", newline="\n") as file:
        file.write(content)
    return True


def _check_up_to_date(path: Path, expected: str) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == expected


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Render docker deployment config artifacts.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated artifacts are up to date instead of rewriting them.",
    )
    return parser


def main() -> int:
    args = build_arg_parser().parse_args()

    rendered_default_env = _render_default_env_file()
    rendered_middleware_env = _render_middleware_env_file()
    rendered_main_compose = _render_compose("main", MAIN_TEMPLATE_PATH)
    rendered_middleware_compose = _render_compose("middleware", MIDDLEWARE_TEMPLATE_PATH)

    outputs = (
        (DEFAULT_ENV_OUTPUT_PATH, rendered_default_env),
        (MIDDLEWARE_ENV_OUTPUT_PATH, rendered_middleware_env),
        (MAIN_COMPOSE_OUTPUT_PATH, rendered_main_compose),
        (MIDDLEWARE_COMPOSE_OUTPUT_PATH, rendered_middleware_compose),
    )

    if args.check:
        stale_paths = [str(path) for path, content in outputs if not _check_up_to_date(path, content)]
        if stale_paths:
            for stale_path in stale_paths:
                print(f"Out of date: {stale_path}", file=sys.stderr)
            return 1
        return 0

    for path, content in outputs:
        _write_if_changed(path, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
